version: "3"

services:
  flexisip:
    build:
      context: flexisip
      dockerfile: Dockerfile
    ports:
      - "5060:5060"
      - "5060:5060/udp"
    volumes:
      - ./flexisip/flex.conf:/etc/flexisip/flexisip.conf
      - ./flexisip/userdb:/etc/flexisip/userdb
