version: "3"

services:
  flexisip:
    build:
      context: flexisip
      dockerfile: Dockerfile
    ports:
      - "5060:5060"
      - "5060:5060/udp"
    volumes:
      - ./flexisip/flexisip.conf:/etc/flexisip/flex.conf
      - ./flexisip/userdb:/etc/flexisip/userdb
    command: ["-c", "/etc/flexisip/flex.conf", "--debug"]
