- name: Install certbot
  apt:
    name: certbot

- name: Renew certbot
  become: true
  ansible.builtin.cron:
    name: Renew certbot
    weekday: 0
    job: certbot renew

- name: Create certificate for server.dieklingel.com
  become: true
  ansible.builtin.shell:
    cmd: |
      certbot certonly --standalone --agree-tos  --noninteractive  -d server.dieklingel.com -m kai.mayer@dieklingel.com
