- name: Installing mosquitto
  become: true
  package:
    name: mosquitto
    state: present

- name: Copy mosquitto.conf file
  become: true
  copy:
    src: .
    dest: /etc/mosquitto
    mode: "0644"
  notify:
    - Restart mosquitto

- name: Interpolate config files
  become: true
  register: template
  ansible.builtin.shell:
    chdir: /etc/mosquitto
    cmd: |
      export ARCH=$(uname -m)
      export ADMIN_USERNAME={{ lookup('ansible.builtin.env', 'ADMIN_USERNAME') }}
      export ADMIN_PASSWORD={{ lookup('ansible.builtin.env', 'ADMIN_PASSWORD') }}

      FILE="{{ item }}"

      CONTENT=$(envsubst < $FILE)
      OLD_CONTENT=$(cat "$FILE%.*" || echo "")

      if [ "$CONTENT" != "$OLD_CONTENT" ]; then
        echo "$CONTENT" > "${FILE%.*}"
        echo "changed"
      fi
  loop:
    - dynamic-security.json.template
    - conf.d/mosquitto_dynamic_security.conf.template
  changed_when:
    - '"changed" in template.stdout'
  notify:
    - Restart mosquitto
